# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Default

steps:
#- task: NodeTool@0
#  inputs:
#    versionSpec: '20.x'
#  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

#Copiar archivos necesarios
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      src/**
      package.json
      package-lock.json
    TargetFolder: '$(Build.ArtifactStagingDirectory)/deploy'
  displayName: 'Copiar archivos para deploy'

#Instalar dependencias de produccion
- script: |
    cd $(Build.ArtifactStagingDirectory)/deploy
    npm install --production
  displayName: 'Instalar dependencias de producci√≥n'

#Empaquetar solo la carpeta deploy
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/deploy'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
  displayName: 'Crear paquete ZIP'

#Publicar papeline Artifact
- task: PublishPipelineArtifact@1
  inputs:
    artifactName: 'nodejs-app'
    targetPath: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Publish pipeline artifact'

#Desplegar en Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'connection2960'  
    appName: 'my-web'          
    package: '$(Build.ArtifactStagingDirectory)/app.zip' 
    deploymentMethod: 'zipDeploy'
    runtimeStack: 'NODE|20-lts'
  displayName: 'Desplegar en Azure Web App'